/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.io.File;
import java.io.PrintWriter;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import operations.ConfigFrame;

/**
 *
 * @author dami
 */
public class PathFrame extends javax.swing.JFrame {

    /**
     * Creates new form PathFrame
     */
    public PathFrame() {
        initComponents();
    }
    
    public PathFrame(JTextField text, int nr) {
        initComponents();
        switch (nr) {
            case 1:
                new ConfigFrame(this, "Otwórz");
                write(text, nr);
                break;
            case 2:
                new ConfigFrame(this, "Zapisz");
                write(text, nr);
                break;
        }
    }
    
    public void write(JTextField text, int nr) {
        try {
            FileNameExtensionFilter f1 = new FileNameExtensionFilter("*.csv", "csv");
            jFileChooser1.setAcceptAllFileFilterUsed(false);
            jFileChooser1.addChoosableFileFilter(f1);
            switch (nr) {
                case 1:
                    jFileChooser1.showOpenDialog(this);
                    break;
                case 2:
                    jFileChooser1.showSaveDialog(this);
                    break;
            }
            jFileChooser1.setApproveButtonText("Zapisz");
            jFileChooser1.setName("Zapis");
            jFileChooser1.setApproveButtonToolTipText("Zapisz");
            
            File plik1 = jFileChooser1.getSelectedFile();
            String s = plik1.getPath();
            
            String[] str = s.split("\\s");
            String p = str[str.length - 1];
            if (p.indexOf(".csv") == -1) {
                s += ".csv";
            }
            text.setText(s);
            /*PrintWriter write = new PrintWriter(s);

            write.println(getToDay());
            for (int i = 0; i < list.size(); i++) {
                if (i != list.size() - 1) {
                    write.println(list.get(i));
                } else {
                    write.print(list.get(i));
                }
            }
            write.close();*/
        } catch (Exception e) {
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PathFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PathFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PathFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PathFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PathFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables
}
