
import com.mongodb.*;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.Map;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dami
 */
public class JFrame extends javax.swing.JFrame {

    public DBCollection col=null;
    /**
     * Creates new form JFrame
     */
    public List<Panel> panels=new ArrayList<>();
    
    public JFrame() {
        initComponents();
        new ConfigFrame(this,"Aplikacja");
        this.setVisible(true);
        
        mongo();
    }

    
    public void mongo()
    {
        int h=0;
        //dodaje nagłówki
        Headline p0 = new Headline();            
        jPanel1.add(p0.jPanel1);
        p0.jPanel1.setLocation(2,h);
        h+=p0.jPanel1.getHeight();
        ///////
        
        try{
        Mongo m = new Mongo("LocalHost",27017);
        
        DB db=m.getDB("MyDB");
        col=db.getCollection("Item");
        
        DBCursor c=col.find();
        System.out.println("JFrame: size: "+c.size());
        
        if(col.find().size()==0)//tzn ze zbior jest pusty
        {
            List<String> list=new ArrayList<>();
            for(int i=0;i<4;i++)list.add("");
            ////////////
            Panel p = new Panel(list,this);         
            jPanel1.add(p.jPanel1);
            p.jPanel1.setLocation(0,h);
            
            h+=p.jPanel1.getHeight();            
            panels.add(p);
        }
        else
        while(c.hasNext())
        {
            DBObject s=c.next();            
            /*List<String> list=new ArrayList<>();
            list.addAll(s.keySet());                              
            System.out.println(list.get(0)+" || "+list);*/            
            /////////
            Map<String,Object> map = s.toMap();
            List<String> list2=new ArrayList<>();
            
            list2.add(map.get("_id").toString());
            list2.add(map.get("Opis_id").toString());
            list2.add(map.get("nazwa").toString());
            list2.add(map.get("cena").toString());
            list2.add(map.get("sprzedane").toString());
            list2.add(map.get("dostepne").toString());
                        /////////dodaje krotki            
            Panel p = new Panel(list2,this);            
            
            p.jPanel1.setLocation(0,h);            
            h+=p.jPanel1.getHeight();       
            jPanel1.add(p.jPanel1);          
            panels.add(p);
            
            ///////////
        }
        //dopasowouje rozmiar panelu
        Dimension d = new Dimension(jPanel1.getWidth()-20,h);
        jPanel1.setPreferredSize(d);        
        jPanel1.revalidate();
        jPanel1.repaint();
        
        System.out.println("JFrame: połączono z mongo");
        }catch(Exception e){System.out.println("JFrame: error: "+e);}
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setDoubleBuffered(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 804, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        jMenu1.setText("Opcje");

        jMenuItem2.setText("dodaj produkt");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // dodaje nowy produkt
        new AddComponent(-1,this);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
