
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import org.math.plot.Plot3DPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dami
 */
public class JFramez2 extends javax.swing.JFrame {

    private List<Punkt3D> lista = new ArrayList<>();
    private List<String> names = new ArrayList<>();
    
    /**
     * Creates new form JFramez8
     */
    public JFramez2() {
        initComponents();
        
        pisz(false);
    }
    
    public JFramez2(List<Punkt3D> lista)
    {
        initComponents();
        
        this.lista=lista;
        pisz(false);
    }
    
    public JFramez2(List<Punkt3D> lista ,String s1,String s2 ,String s3)
    {
        initComponents();
        
        this.lista=lista;
        names.add(s1);
        names.add(s2);
        names.add(s3);
        
        pisz(true);
    }
    
    public void setLista(List<Punkt3D> lista)
    {
        this.lista=lista;
    }
    
    private double[][] Tablica()
    {
        double[][] xyz = new double[lista.size()][];
        if(lista.size()==0)
        {
            return Tablica2();
        }
        
        for(int i=0;i<lista.size();i++)
        {
            double[] p ={lista.get(i).x , lista.get(i).y , lista.get(i).z};
            xyz[i]=p;
        }
        
        return xyz;
    }
    
    private double[][] Tablica2()
    {
        double[][] xyz = {{1,2,3,4,5,6,7,8,9}, {2,5,6,7,8,3,2,0,1}, {2,5,6,7,8,3,2,0,1}};
        
        return xyz;
    }
    
    
    public void pisz(boolean nazwa)
    {
        //this.setSize(600,600);
        //double[][] xyz = {{1}, {2}, {2}};
        //double[][] xyz = {{1,2,3,4,5,6,7,8,9}, {2,5,6,7,8,3,2,0,1}, {2,5,6,7,8,3,2,0,1}};
        double[][] xyz = Tablica();
                
        // create your PlotPanel (you can use it as a JPanel)
        Plot3DPanel plot = new Plot3DPanel();

        // define the legend position
        plot.addLegend("SOUTH");

        // add a line plot to the PlotPanel
        plot.addScatterPlot("Wykres", xyz);
        
        
        if(nazwa)
        {
        plot.getAxis(0).setLegend(names.get(0));
        plot.getAxis(1).setLegend(names.get(1));
        plot.getAxis(2).setLegend(names.get(2));
        }
        
        // put the PlotPanel in a JFrame like a JPanel
        //this = new JFrame("a plot panel");
        this.setTitle("Wykres 3D");
        this.setSize(600, 600);
        this.setContentPane(plot);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramez2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramez2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramez2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramez2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramez2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
