
import java.util.ArrayList;
import java.util.List;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dami
 */
public class JFramezzz13z extends javax.swing.JFrame {

    public int tryb = 0; //0 tryb klasyfikacji , 1 oceny
    public JFramez3 app = null;
    
    /**
     * Creates new form JFramezzz12z
     */
    public JFramezzz13z() {
        initComponents();
        
        this.setTitle("Drzewo decyzyjne");
        
        try {
        UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        SwingUtilities.updateComponentTreeUI(this);
        this.pack();
        } 
        catch (Exception e) {}        
        this.setVisible(true);
    }
    
    
    public JFramezzz13z(JFramez3 fr3 ,int tryb) {
        initComponents();
                
        try {
        UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        SwingUtilities.updateComponentTreeUI(this);
        this.pack();
        } 
        catch (Exception e) {}        
        this.setVisible(true);
        
        this.app=fr3;
        this.tryb=tryb;
        
        if(this.tryb==0)
        {this.setTitle("Klasyfikacja drzewa decyzyjnego");}
        else
        {this.setTitle("Ocena drzewa decyzyjnego");}
        pisz();
    }
    
    public void pisz()
    {
        //wypelniam jcombobox'y
        List<String> list=app.frame.kol.Naglow();
        
        jComboBox1.removeAllItems();
        for(int i=0;i<list.size();i++)//dodaje naglowki do jComboBox1
        jComboBox1.addItem(list.get(i));                
    }
    
    public void tryb(String trybb)
    {
        int klasa = jComboBox1.getSelectedIndex();
        
        int stopien=1;
        
        try{//jesli bedzie nie poprawne to pozostanie 0
        stopien = Integer.valueOf(jTextField1.getText());
        }catch(Exception e){}
        
        if(stopien<=0){stopien=1;}//nie moge dzielic na 0 zbiorow
        if(stopien>app.frame.kol.ileWierszy())
        {
            stopien = app.frame.kol.ileWierszy();//jesli rozmiar jest za duzy
        }
        
        zzDrzewo drzewo = new zzDrzewo();
        
        ////tu bedzie sie roznic
        if(trybb.equals("klasyfikacji"))
        {
            List<String> list = drzewo.drzewo_normalne(app.frame.kol, klasa, stopien);
            
            dopisz(list);
            
            zMetody1 met = new zMetody1();
            
            double p = met.Trafnosc(list, app.frame.kol.kolumna(klasa));
            jTextArea2.setText("trafność klasyfikacji: "+p);
            
            
            //this.setVisible(false);
        }
        
        if(trybb.equals("oceny"))
        {
            List<String> list = drzewo.ocena(app.frame.kol, klasa, stopien);
            
            dopisz(list);           
            
            double jakosc = drzewo.ocena2(list);
            
            jTextArea2.setText("ocena jakosci klasyfikacji: "+jakosc);
            
            
            //this.setVisible(false);
        }
        
        //dodaje to do danych
    }
    
    private void dopisz(List<String> list)
    {
        List<String> list3 = app.frame.kol.getLinie();
        int l=0;
        
        for(int i=0;i<list3.size();i++)
        System.out.println(list3.get(i));
        System.out.println();
            
        if(app.frame.kol.naglowki)//jeśli są nagłówki
        {
            //dodaje nagłówek
            list3.set(0, list3.get(0)+";"+"Ocena"+(app.frame.kol.ileKolumn()+1)+" drzewa");
            l=1;
        }
        
        for(;l<list3.size();l++)
        {
                //System.out.println(list3.get(i));
            if(app.frame.kol.naglowki)
            list3.set(l, list3.get(l)+";"+list.get(l-1));
            else
            list3.set(l, list3.get(l)+";"+list.get(l)); 
        }
        
        app.frame.kol.setLinie(list3);
                    
        
        app.update();        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Klasa decyzyjna        :");

        jLabel2.setText("Stopień dyskretyzacji:");

        jTextField1.setText("1");

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jButton1.setText("Potwierdź");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // wykonuje ocene lub klasyfikajcie
        
        if(tryb==0){this.tryb("klasyfikacji");}
        if(tryb==1){this.tryb("oceny");}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramezzz13z.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramezzz13z.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramezzz13z.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramezzz13z.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramezzz13z().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
