package tables;
// Generated 2018-09-07 10:23:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Competition generated by hbm2java
 */
public class Competition  implements java.io.Serializable {


     private int id;
     private String dateOfCompetitionBegin;
     private String title;
     private String description;
     private Set participations = new HashSet(0);

    public Competition() {
    }

	
    public Competition(int id) {
        this.id = id;
    }
    public Competition(int id, String dateOfCompetitionBegin, String title, String description) {
       this.id = id;
       this.dateOfCompetitionBegin = dateOfCompetitionBegin;
       this.title = title;
       this.description = description;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDateOfCompetitionBegin() {
        return this.dateOfCompetitionBegin;
    }
    
    public void setDateOfCompetitionBegin(String dateOfCompetitionBegin) {
        this.dateOfCompetitionBegin = dateOfCompetitionBegin;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getParticipations() {
        return this.participations;
    }
    
    public void setParticipations(Set participations) {
        this.participations = participations;
    }




}


