package tables;
// Generated 2018-09-07 10:23:55 by Hibernate Tools 4.3.1



/**
 * Participation generated by hbm2java
 */
public class Participation  implements java.io.Serializable {


     private int id;
     private Competition competition;
     private User user;
     private Integer position;

    public Participation() {
    }

	
    public Participation(int id) {
        this.id = id;
    }
    public Participation(int id, Competition competition, User user) {
       this.id = id;
       this.competition = competition;
       this.user = user;
       this.position = 0;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Competition getCompetition() {
        return this.competition;
    }
    
    public void setCompetition(Competition competition) {
        this.competition = competition;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Integer getPosition() {
        return this.position;
    }
    
    public void setPosition(Integer position) {
        this.position = position;
    }




}


