package tables;
// Generated 2018-09-07 10:23:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private int id;
     private String login;
     private String password;
     private String role;
     private Set participations = new HashSet(0);

    public User() {
    }

	
    public User(int id) {
        this.id = id;
    }
    public User(int id, String login, String password) {
       this.id = id;
       this.login = login;
       this.password = password;
       this.role = "USER";
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public Set getParticipations() {
        return this.participations;
    }
    
    public void setParticipations(Set participations) {
        this.participations = participations;
    }




}


